"""
配置编辑器字段悬停提示文案。
"""

from __future__ import annotations


FIELD_TOOLTIPS: dict[str, str] = {
    "section.project": "项目分组主要管理项目资料位置、输入文件和输出目录。通常先把这里配对，其他参数才有意义。",
    "section.writing": "写作分组决定模型写作口径、篇幅目标和格式约束。大多数业务效果调整都先看这里。",
    "section.processing": "处理路径分组决定采购需求和评分标准走哪条业务链路，是最关键的业务开关。",
    "section.runtime": "运行分组控制流式输出、trace、文件输出和调试行为。普通用户一般只需要改少数字段。",
    "project.root_dir": "项目资料根目录。大纲、采购需求、评分标准和输出目录通常都相对这个目录解析；换项目时优先检查这里。",
    "project.bidder_name": "投标主体名称。会进入提示词和部分输出内容，用来让正文更贴近当前投标主体。",
    "project.outline_file": "章节大纲文件路径。系统会按这个 Markdown 大纲生成树结构和章节写作任务。",
    "project.bid_requirements_mode": "决定采购需求是引用外部文件，还是直接把正文写进 YAML。长期维护更推荐文件模式。",
    "project.bid_requirements_file": "采购需求源文件路径。通常指向招标文件中整理出的采购需求 Markdown。",
    "project.bid_requirements_text": "内嵌采购需求正文。只适合临时配置或小型样例，正式项目更建议拆到独立文件。",
    "project.scoring_criteria_mode": "决定评分标准是引用外部文件，还是直接写进 YAML。正式项目通常推荐文件模式。",
    "project.scoring_criteria_file": "评分标准源文件路径。系统会从这里提取评分关注点和命中证据。",
    "project.scoring_criteria_text": "内嵌评分标准正文。适合快速试验，但大文档放在 YAML 里会越来越难维护。",
    "project.output_dir": "正文输出目录。生成的章节文件、调试 sidecar 和部分缓存都会落到这里或其子目录。",
    "writing.role_mode": "决定角色设定来自文件还是内嵌文本。团队复用配置时，通常更建议 role_file。",
    "writing.role_file": "角色提示词文件。适合保存一整套行业背景、写作口径和身份设定，避免在 YAML 里重复粘贴长文本。",
    "writing.role_text": "内嵌角色正文。适合快速实验；如果会长期使用，建议迁移到 role_file。",
    "writing.target_words.default": "默认目标篇幅基准值。运行时会基于它自动推导目标区间，并把区间写入 prompt。",
    "writing.target_words.min": "目标篇幅基准值允许的最小值。界面里的生成参数不能低于它。",
    "writing.target_words.max": "目标篇幅基准值允许的最大值。用来避免一次把单章篇幅基准调得过大。",
    "writing.target_words.step": "篇幅基准调节步长。也会用于把自动推导的区间上沿向上取整。",
    "writing.target_words.upper_ratio": "目标区间上沿相对基准值的倍率。例如 1.15 表示 3000 会自动推导为约 3000-3500 字。",
    "writing.max_tables_per_section": "单节允许出现的最大表格数。数值越大，模型越容易输出表格。",
    "writing.max_mermaid_flowcharts_per_section": "单节允许出现的 Mermaid 图示上限。设为 0 时不注入流程图控制提示。",
    "writing.extra_rules_text": "补充写作规则，每行一条。当前会追加到“结构输出硬要求”的末尾，适合放必须跟随结构要求一起传达的业务写作口径。",
    "processing.path": "当前项目的主处理路径。编辑器当前提供 auto 和 full_context 两个入口：auto 会做章节级检索与分类，full_context 会直接把采购需求和评分标准全文拼入提示词。",
    "processing.project_background.enabled": "是否根据采购需求注入 H2 项目背景材料。该配置只服务 auto 链路；full_context 会直接注入完整材料，不再额外提炼项目背景。",
    "processing.project_background.max_chars": "summary 模式下项目背景摘要的目标长度上限。excerpts 模式下该输入会置灰，摘录长度由证据字符上限控制。",
    "processing.project_background.h2.precompute_on_batch": "后端兼容字段；当前配置编辑器不展示，GUI 批量生成暂未接入预生成阶段。",
    "processing.project_background.h2.generate_missing_on_single": "单章节生成时，如果当前 H2 背景缓存缺失，是否先补生成一次。",
    "processing.project_background.h2.max_evidence_blocks": "H2 背景生成最多使用多少个采购需求证据片段。",
    "processing.project_background.h2.max_evidence_chars": "H2 背景生成使用的证据片段总字符上限。",
    "processing.project_background.h2.content_mode": "H2 背景内容模式。excerpts 直接使用采购需求原文摘录；summary 调用辅助模型生成摘要。",
    "processing.project_background.h2.min_evidence_blocks": "生成 H2 背景所需的最少证据片段数；低于该值会触发回退。",
    "processing.project_background.h2.fallback": "H2 背景失败时的回退策略：raw_evidence 使用原文片段，empty 不注入背景。",
    "processing.project_background.h2.cache_dir": "H2 项目背景 JSON 缓存目录，通常相对项目根目录解析。",
    "processing.full_context.chapter_writing_plan.enabled": "是否在 full_context 模式下先生成一个章节写作计划，并把它插入章节任务卡。开启后会增加一次辅助 LLM 调用。",
    "processing.full_context.chapter_writing_plan.max_chars": "章节写作计划的长度上限。建议保持简短，只做提纲，不要让它挤占正文生成的上下文空间。",
    "processing.legacy_rule.scoring_max_rows": "legacy_rule 下最多保留多少条评分项。数值太小可能漏要求，太大则会稀释重点。",
    "processing.hybrid_extract.unavailable_policy": "hybrid_extract 不可用时的处理策略。fallback_legacy 更稳，fail_fast 更严格。",
    "processing.hybrid_extract.scoring_parse_mode": "评分标准解析模式。auto 会自动判断表格或文本，通常先保持 auto。",
    "processing.hybrid_extract.scoring_max_rows": "hybrid_extract 下最终保留的评分项条数。它决定进入 prompt 的评分关注密度。",
    "processing.hybrid_extract.retrieval.lexical_enabled": "是否启用 lexical 检索。当前 hybrid_extract 的基础能力依赖它，通常不要关闭。",
    "processing.hybrid_extract.retrieval.vector_enabled": "是否启用向量检索。能提升同义表达召回，但需要 embedding 连接已配置。",
    "processing.hybrid_extract.retrieval.verify_enabled": "是否启用候选校验。能提高精度，但需要 pruning 连接配置，成本也更高。",
    "processing.hybrid_extract.retrieval.top_k_lexical": "lexical 检索的候选数。数值越大，召回更广，但后续排序成本更高。",
    "processing.hybrid_extract.retrieval.top_k_vector": "vector 检索的候选数。只有启用向量检索时才生效。",
    "processing.hybrid_extract.retrieval.top_k_fused": "两路候选融合后的保留数。主要影响后续精排和最终摘录范围。",
    "processing.hybrid_extract.retrieval.top_k_final": "最终进入摘录或校验阶段的候选数。过小可能漏关键证据，过大则会分散注意力。",
    "processing.hybrid_extract.retrieval.min_fused_score": "候选最小融合分。提高它可以更严格，但过高可能导致召回不足。",
    "processing.hybrid_extract.quote_only": "是否强制只允许原文摘录。通常建议开启，能减少模型自由改写证据。",
    "processing.hybrid_extract.return_ids_only": "是否只让校验模型返回片段 ID。一般建议保持 true，便于程序回填原文。",
    "processing.hybrid_extract.verify_max_candidates": "送入 verifier 的最多候选数。越大越全面，但调用成本更高。",
    "runtime.stream.enabled": "是否启用流式输出。开启后生成过程会更有即时反馈。",
    "runtime.stream.idle_timeout_seconds": "流式输出最后一个 token 后的静默收尾时间。接口偶尔收尾慢时可适当调大。",
    "runtime.trace.enabled": "是否记录生成 trace。排查 prompt、上下文或输出问题时很有用。",
    "runtime.trace.directory": "trace 输出目录，按配置文件目录解析。排查问题时可以到这里看 prompt、上下文和摘要。",
    "runtime.trace.mode": "trace 记录级别。full 更完整，basic 更轻量。",
    "runtime.trace.write_prompt": "是否把最终 prompt 写入 trace。排查提示词问题时通常建议开启。",
    "runtime.trace.write_output": "是否把生成正文写入 trace。需要回看模型原始输出时很有帮助。",
    "runtime.trace.write_context": "是否写入上下文裁剪和拼接细节。分析命中逻辑时建议开启。",
    "runtime.trace.write_summary": "是否输出摘要文件。想快速看本次生成概况时建议开启。",
    "runtime.trace.redact_sensitive": "是否在 trace 中脱敏敏感信息。一般建议保持开启。",
    "runtime.debug.context_pruning_dump": "是否额外输出 context pruning 的调试 sidecar。只在排查章节命中问题时建议打开。",
    "runtime.output.prefix": "输出文件名前缀。需要按项目或批次区分输出文件时可填写。",
    "runtime.output.include_title_header": "保存正文时是否自动加入标题头。通常用于控制文件落盘格式，而不是模型写作本身。",
    "runtime.output.overwrite_existing": "是否覆盖已有输出。关闭后会保留历史版本，更安全，但目录里文件会变多。",
    "runtime.output.filename_max_length": "输出文件名最大长度。主要用于避免路径过长或文件名过长的问题。",
    "runtime.output.empty_filename_fallback": "标题无法生成有效文件名时的兜底名称。一般保持默认即可。",
    "runtime.merge.normalize_soft_line_breaks": "整合标书时是否归一化软回车。遇到复制粘贴换行混乱时可开启。",
}


def get_tooltip_text(key: str) -> str:
    return FIELD_TOOLTIPS.get(key, "")
