"""
配置编辑器字段悬停提示文案。
"""

from __future__ import annotations


FIELD_TOOLTIPS: dict[str, str] = {
    "section.project": "项目分组主要管理项目资料位置、输入文件和输出目录。通常先把这里配对，其他参数才有意义。",
    "section.writing": "写作分组决定模型写作口径、篇幅目标和格式约束。大多数业务效果调整都先看这里。",
    "section.processing": "处理路径分组决定采购需求和评分标准走哪条业务链路，是最关键的业务开关。",
    "section.models": "模型分组只编辑非敏感模型参数。API Key、Base URL 这类敏感连接信息不在这里保存。",
    "section.runtime": "运行分组控制流式输出、trace、文件输出和调试行为。普通用户一般只需要改少数字段。",
    "project.root_dir": "项目资料根目录。大纲、采购需求、评分标准和输出目录通常都相对这个目录解析；换项目时优先检查这里。",
    "project.bidder_name": "投标主体名称。会进入提示词和部分输出内容，用来让正文更贴近当前投标主体。",
    "project.outline_file": "章节大纲文件路径。系统会按这个 Markdown 大纲生成树结构和章节写作任务。",
    "project.bid_requirements_mode": "决定采购需求是引用外部文件，还是直接把正文写进 YAML。长期维护更推荐文件模式。",
    "project.bid_requirements_file": "采购需求源文件路径。通常指向招标文件中整理出的采购需求 Markdown。",
    "project.bid_requirements_text": "内嵌采购需求正文。只适合临时配置或小型样例，正式项目更建议拆到独立文件。",
    "project.scoring_criteria_mode": "决定评分标准是引用外部文件，还是直接写进 YAML。正式项目通常推荐文件模式。",
    "project.scoring_criteria_file": "评分标准源文件路径。系统会从这里提取评分关注点和命中证据。",
    "project.scoring_criteria_text": "内嵌评分标准正文。适合快速试验，但大文档放在 YAML 里会越来越难维护。",
    "project.output_dir": "正文输出目录。生成的章节文件、调试 sidecar 和部分缓存都会落到这里或其子目录。",
    "writing.role_mode": "决定角色设定来自文件还是内嵌文本。团队复用配置时，通常更建议 role_file。",
    "writing.role_file": "角色提示词文件。适合保存一整套行业背景、写作口径和身份设定，避免在 YAML 里重复粘贴长文本。",
    "writing.role_text": "内嵌角色正文。适合快速实验；如果会长期使用，建议迁移到 role_file。",
    "writing.target_words.default": "默认目标篇幅基准值。运行时会基于它自动推导目标区间，并把区间写入 prompt。",
    "writing.target_words.min": "目标篇幅基准值允许的最小值。界面里的生成参数不能低于它。",
    "writing.target_words.max": "目标篇幅基准值允许的最大值。用来避免一次把单章篇幅基准调得过大。",
    "writing.target_words.step": "篇幅基准调节步长。也会用于把自动推导的区间上沿向上取整。",
    "writing.target_words.upper_ratio": "目标区间上沿相对基准值的倍率。例如 1.15 表示 3000 会自动推导为约 3000-3500 字。",
    "writing.output_format": "输出格式说明，会直接影响提示词中对正文形态的要求。通常只有切换写作风格时才需要改。",
    "writing.first_line_template": "章节正文首行模板。留空时不强制插入固定首行；需要固定起句时再设置。",
    "writing.allow_markdown_headings": "是否允许正文里出现 Markdown 标题符号。政府标书正文通常建议关闭。",
    "writing.allow_english_terms": "是否允许必要英文术语。专业场景可开启，但一般不建议让正文出现过多英文混排。",
    "writing.max_tables_per_section": "单节允许出现的最大表格数。数值越大，模型越容易输出表格。",
    "writing.max_mermaid_flowcharts_per_section": "单节允许出现的 Mermaid 图示上限。设为 0 时不注入流程图控制提示。",
    "writing.summary_title": "章节小结标题名称。若不希望正文出现小结标题，可以结合提示词策略一起调整。",
    "writing.hard_constraints_text": "高优先级硬约束，每行一条。这里适合写绝对不能违反的格式规则和禁用表达。",
    "writing.extra_rules_text": "补充写作规则，每行一条。当前会追加到“结构输出硬要求”的末尾，适合放必须跟随结构要求一起传达的业务写作口径。",
    "processing.path": "当前项目的主处理路径。编辑器当前提供 auto 和 full_context 两个入口：auto 会做章节级检索与分类，full_context 会直接把采购需求和评分标准全文拼入提示词。",
    "processing.context_view.include_ancestors": "是否把当前章节的父级标题链一起带入局部上下文。通常建议开启，便于模型理解章节定位。",
    "processing.context_view.include_siblings": "是否把同级标题带入局部上下文。开启后更利于避免跨章节重复。",
    "processing.context_view.max_siblings": "最多保留多少个同级标题。值越大，上下文更全，但 prompt 也会更长。",
    "processing.project_background.enabled": "是否根据采购需求生成一段项目背景摘要。当前它会在 auto 和 full_context 两种模式下生效。",
    "processing.project_background.max_chars": "项目背景摘要的目标长度上限。值越大，背景更完整，但 prompt 也会更长。",
    "processing.full_context.chapter_writing_plan.enabled": "是否在 full_context 模式下先生成一个章节写作计划，并把它插入章节任务卡。开启后会增加一次辅助 LLM 调用。",
    "processing.full_context.chapter_writing_plan.max_chars": "章节写作计划的长度上限。建议保持简短，只做提纲，不要让它挤占正文生成的上下文空间。",
    "processing.legacy_rule.scoring_max_rows": "legacy_rule 下最多保留多少条评分项。数值太小可能漏要求，太大则会稀释重点。",
    "processing.legacy_rule.requirements_max_quotes": "legacy_rule 下最多摘录多少条采购需求片段。通常 3 到 6 比较稳。",
    "processing.legacy_rule.requirements_max_quote_chars": "legacy_rule 下单条需求摘录的最大长度。主要用来限制 prompt 膨胀。",
    "processing.legacy_rule.requirement_brief_enabled": "是否启用需求 brief。开启后会把命中的需求再压缩成更短的摘要视角。",
    "processing.legacy_rule.requirement_brief_fallback": "需求 brief 失败时的回退策略。一般保持默认即可，不建议普通用户频繁改。",
    "processing.hybrid_extract.unavailable_policy": "hybrid_extract 不可用时的处理策略。fallback_legacy 更稳，fail_fast 更严格。",
    "processing.hybrid_extract.scoring_parse_mode": "评分标准解析模式。auto 会自动判断表格或文本，通常先保持 auto。",
    "processing.hybrid_extract.scoring_max_rows": "hybrid_extract 下最终保留的评分项条数。它决定进入 prompt 的评分关注密度。",
    "processing.hybrid_extract.requirements_max_quotes": "hybrid_extract 下最终保留的采购需求摘录条数。数值越大，证据越多，但 prompt 更长。",
    "processing.hybrid_extract.requirements_max_quote_chars": "hybrid_extract 下单条摘录的最大字符数。主要控制摘录长度和 prompt 开销。",
    "processing.hybrid_extract.requirement_brief_enabled": "hybrid_extract 下是否额外生成需求 brief。想强调摘要视图时再开。",
    "processing.hybrid_extract.requirement_brief_fallback": "hybrid_extract 的需求 brief 失败回退策略。一般建议保持默认。",
    "processing.hybrid_extract.retrieval.lexical_enabled": "是否启用 lexical 检索。当前 hybrid_extract 的基础能力依赖它，通常不要关闭。",
    "processing.hybrid_extract.retrieval.vector_enabled": "是否启用向量检索。能提升同义表达召回，但需要 embedding 连接已配置。",
    "processing.hybrid_extract.retrieval.verify_enabled": "是否启用候选校验。能提高精度，但需要 pruning 连接配置，成本也更高。",
    "processing.hybrid_extract.retrieval.top_k_lexical": "lexical 检索的候选数。数值越大，召回更广，但后续排序成本更高。",
    "processing.hybrid_extract.retrieval.top_k_vector": "vector 检索的候选数。只有启用向量检索时才生效。",
    "processing.hybrid_extract.retrieval.top_k_fused": "两路候选融合后的保留数。主要影响后续精排和最终摘录范围。",
    "processing.hybrid_extract.retrieval.top_k_final": "最终进入摘录或校验阶段的候选数。过小可能漏关键证据，过大则会分散注意力。",
    "processing.hybrid_extract.retrieval.min_fused_score": "候选最小融合分。提高它可以更严格，但过高可能导致召回不足。",
    "processing.hybrid_extract.quote_only": "是否强制只允许原文摘录。通常建议开启，能减少模型自由改写证据。",
    "processing.hybrid_extract.return_ids_only": "是否只让校验模型返回片段 ID。一般建议保持 true，便于程序回填原文。",
    "processing.hybrid_extract.verify_max_candidates": "送入 verifier 的最多候选数。越大越全面，但调用成本更高。",
    "models.generation.model": "主生成模型名称。决定正文写作使用哪个模型，是最直接影响生成质量的参数之一。",
    "models.generation.temperature": "主生成模型温度。值越高越发散，值越低越稳定；标书场景通常不建议太高。",
    "models.generation.max_tokens": "主生成模型单次输出上限。太小会截断，太大则可能增加成本和时延。",
    "models.generation.timeout_seconds": "主生成模型超时时间。接口较慢时可适当增大，但一般不建议频繁调整。",
    "models.generation.max_retries": "主生成模型最大重试次数。网络波动较大时可稍增，避免单次失败直接中断。",
    "models.generation.top_p": "可选采样参数。大多数情况下留空或保持默认即可，不懂时不要和 temperature 一起频繁调。",
    "models.generation.seed": "可选随机种子。需要更稳定复现结果时再设置。",
    "models.pruning.model": "辅助模型名称。主要用于 brief、校验或轻量提炼，不直接负责正文写作。",
    "models.pruning.temperature": "辅助模型温度。通常建议低一些，让摘要和校验更稳定。",
    "models.pruning.max_tokens": "辅助模型输出上限。只做短摘要或 ID 选择时，一般不需要太大。",
    "models.pruning.timeout_seconds": "辅助模型超时时间。辅助链路较慢时可调大，但普通用户通常不用改。",
    "models.pruning.max_retries": "辅助模型最大重试次数。主要用于提高不稳定接口下的成功率。",
    "models.pruning.top_p": "辅助模型可选采样参数。一般保持空或默认即可。",
    "models.pruning.seed": "辅助模型可选随机种子。需要复现实验结果时再设置。",
    "models.embedding.model": "embedding 模型名称。用于向量检索，不直接生成正文。",
    "models.embedding.batch_size": "批量生成向量时每批处理的数量。值越大越快，但也更吃接口和内存。",
    "models.embedding.cache_dir": "向量缓存目录。命中文档缓存后可以避免重复生成 embedding。",
    "models.embedding.rebuild_on_source_change": "源文变化后是否自动重建向量缓存。通常建议开启，避免旧缓存误导召回。",
    "models.embedding.query_prefix": "查询文本前缀。只有你明确知道 embedding 服务需要特定前缀时再改。",
    "models.embedding.document_prefix": "文档文本前缀。通常配合特定 embedding 模型策略使用，不懂时保持默认。",
    "runtime.stream.enabled": "是否启用流式输出。开启后生成过程会更有即时反馈。",
    "runtime.stream.idle_timeout_seconds": "流式输出最后一个 token 后的静默收尾时间。接口偶尔收尾慢时可适当调大。",
    "runtime.trace.enabled": "是否记录生成 trace。排查 prompt、上下文或输出问题时很有用。",
    "runtime.trace.directory": "trace 输出目录，按配置文件目录解析。排查问题时可以到这里看 prompt、上下文和摘要。",
    "runtime.trace.mode": "trace 记录级别。full 更完整，basic 更轻量。",
    "runtime.trace.write_prompt": "是否把最终 prompt 写入 trace。排查提示词问题时通常建议开启。",
    "runtime.trace.write_output": "是否把生成正文写入 trace。需要回看模型原始输出时很有帮助。",
    "runtime.trace.write_context": "是否写入上下文裁剪和拼接细节。分析命中逻辑时建议开启。",
    "runtime.trace.write_summary": "是否输出摘要文件。想快速看本次生成概况时建议开启。",
    "runtime.trace.redact_sensitive": "是否在 trace 中脱敏敏感信息。一般建议保持开启。",
    "runtime.debug.context_pruning_dump": "是否额外输出 context pruning 的调试 sidecar。只在排查章节命中问题时建议打开。",
    "runtime.output.prefix": "输出文件名前缀。需要按项目或批次区分输出文件时可填写。",
    "runtime.output.include_title_header": "保存正文时是否自动加入标题头。通常用于控制文件落盘格式，而不是模型写作本身。",
    "runtime.output.overwrite_existing": "是否覆盖已有输出。关闭后会保留历史版本，更安全，但目录里文件会变多。",
    "runtime.output.filename_max_length": "输出文件名最大长度。主要用于避免路径过长或文件名过长的问题。",
    "runtime.output.empty_filename_fallback": "标题无法生成有效文件名时的兜底名称。一般保持默认即可。",
    "runtime.merge.normalize_soft_line_breaks": "整合标书时是否归一化软回车。遇到复制粘贴换行混乱时可开启。",
}


def get_tooltip_text(key: str) -> str:
    return FIELD_TOOLTIPS.get(key, "")
