# Local API settings for Bid Writer. This file is ignored by Git.
BID_WRITER_TEMPERATURE=0.8
BID_WRITER_MAX_TOKENS=10000

BID_WRITER_API_BASE_URL=https://api.codexzh.com/v1
BID_WRITER_MODEL=gpt-5.4
BID_WRITER_API_KEY=sk-LCDlVAQZuIsBIiBK2VhaDkrMRO5zPRmiU8OeltwFwH7jdEqX

BID_WRITER_PRUNING_API_BASE_URL=https://api.codexzh.com/v1
BID_WRITER_PRUNING_API_KEY=sk-LCDlVAQZuIsBIiBK2VhaDkrMRO5zPRmiU8OeltwFwH7jdEqX
BID_WRITER_PRUNING_MODEL=gpt-5.4

BID_WRITER_EMBEDDING_API_BASE_URL=https://api.ssopen.top/v1
BID_WRITER_EMBEDDING_API_KEY=sk-Wx0a21H1KtSwq6otS9AoGAMCcHX395lpixPdEhdt2Y1YH4lK
